export enum EQClass {
    Bard = 'Bard',
    Beastlord = 'Beastlord',
    Beserker = 'Beserker',
    Cleric = 'Cleric',
    Druid = 'Druid',
    Enchanter = 'Enchanter',
    Magician = 'Magician',
    Monk = 'Monk',
    Necromancer = 'Necromancer',
    Paladin = 'Paladin',
    Ranger = 'Ranger',
    Rogue = 'Rogue',
    Shadowknight = 'Shadowknight',
    Shaman = 'Shaman',
    Warrior = 'Warrior',
    Wizard = 'Wizard',
}