const servers: ReadonlyMap<number, string> = new Map([
	[0, 'Aradune'],
	[1, 'Mischief'],
	[2, 'Oakwynd'],
	[3, 'Rizlona'],
	[4, 'Thornblade'],
	[5, 'Vaniki'],
	[6, 'Vox'],
	[7, 'Yelinak'],
	[8, 'Agnarr'],
	[9, 'AntoniusBayle'],
	[10, 'BertoxxulousSaryrn'],
	[11, 'BristlebaneTheTribunal'],
	[12, 'CazicThuleFenninRo'],
	[13, 'DrinalMaelinStarpyre'],
	[14, 'Mangler'],
	[15, 'ErollisiMarrTheNameless'],
	[16, 'FirionaVie'],
	[17, 'LuclinStromm'],
	[18, 'PovarQuellious'],
	[19, 'Ragefire'],
	[20, 'TheRathePrexus'],
	[21, 'TunareTheSeventhHammer'],
	[22, 'XegonyDruzzilRo'],
	[23, 'Zek'],
]);
export default servers;