const servers: ReadonlyArray<string> = [
	'Aradune',
	'Mischief',
	'Oakwynd',
	'Rizlona',
	'Thornblade',
	'Vaniki',
	'Vox',
	'Yelinak',
	'Agnarr',
	'AntoniusBayle',
	'BertoxxulousSaryrn',
	'BristlebaneTheTribunal',
	'CazicThuleFenninRo',
	'DrinalMaelinStarpyre',
	'Mangler',
	'ErollisiMarrTheNameless',
	'FirionaVie',
	'LuclinStromm',
	'PovarQuellious',
	'Ragefire',
	'TheRathePrexus',
	'TunareTheSeventhHammer',
	'XegonyDruzzilRo',
	'Zek',
];
export default servers;