FROM node:alpine
WORKDIR /app
COPY /client/localhost.pem /client/localhost.key ./
COPY /client/.parcelrc /client/package.json /client/package-lock.json ./
RUN npm ci
COPY ./client/ .
EXPOSE 1234
CMD npm run start
