FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /app
COPY /server/LootGod.csproj ./
RUN dotnet restore
COPY /server/ .
EXPOSE 8080
CMD ["dotnet", "watch", "--non-interactive", "--no-hot-reload"]
