# fly.toml file generated for raidloot

app = "raidloot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DATABASE_URL = "/mnt/guildLoot.db"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/mnt"
  source = "loot"

[build.args]
  REACT_APP_TITLE = "Raid Loot"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 2000
    soft_limit = 2000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = 30000
    grace_period = "5s"
    method = "get"
    path = "/test"
    protocol = "http"
    restart_limit = 0
    timeout = 3000
    tls_skip_verify = false
    [services.http_checks.headers]
