# fly.toml file generated for raidloot

app = "raidloot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DATABASE_URL = "/mnt/guildLoot.db"
  ROT_LOOT_URL = "https://rotloot.fly.dev"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/mnt"
  source = "loot"

[build.args]
  REACT_APP_API_PATH = ""
  REACT_APP_TITLE = "Raid Loot"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 2000
    soft_limit = 2000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
